#server 重新配置端口号,项目名和热部署
server:
  port: 8231
  context-path: /springboot

#相关的spring数据源的配置信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: 212216
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
